### ISSUE TITLE
Deadlock after call CS104_Connection_sendInterrogationCommand in ConnectionHandler

### ISSUE THREAD

**Issue by koohestani** [mz-automation/lib60870#135]
In our program, we have encountered a deadlock issue when we call CS104_Connection_sendInterrogationCommand after receiving a STARTDT event in the ConnectionHandler. We are unsure if this behavior is reasonable, as this problem only surfaced after commit [219c892](https://github.com/mz-automation/lib60870/commit/219c892aecbe51ed38cbefde102714ad515af124), and it does not exist in version v2.3.1.

**Comment by mzillgith** [comment]
This is probably the same issue as #134.

If so it should be fixed with commit https://github.com/mz-automation/lib60870/commit/da1b97ff97d928fcbc58f9aa09fbfc0488fe4f97

**Comment by koohestani** [comment]
> This is probably the same issue as #134.
> 
> If so it should be fixed with commit [da1b97f](https://github.com/mz-automation/lib60870/commit/da1b97ff97d928fcbc58f9aa09fbfc0488fe4f97)

We test with the latest commit https://github.com/mz-automation/lib60870/commit/da1b97ff97d928fcbc58f9aa09fbfc0488fe4f97 and the problem still exists.

**Comment by a-m-farahani** [comment]
Same problem here, and the latest commit doesn't seem to fix the issue.
